language: objective-c  #1
osx_image: xcode11.3 #2
xcode_project: CIDemo.xcodeproj #3
xcode_scheme: CIDemo #4
xcode_sdk: iphonesimulator13.3 #5
jobs:
include:
 # - stage: Swiflint
   # script:
   #   - ./Pods/SwiftLint/swiftlint --reporter junit

  - stage: XCTest
    script:
      - fastlane scan -s demoTest

  - stage: XCTest
    script:
      - fastlane scan -s demoUITest
